### ISSUE TITLE
Add enabled fields to delete customer dialog

### ISSUE THREAD

**Issue by renemadsen** [microting/eform-angular-basecustomer-plugin#8]
**The steps to reproduce the bug**
Go to lists of customers.
Delete a customer.
The warning dialog is presented

**The expected behavior of the application**
The dialog should show all fields enabled for customers, so it's clear for the user, which customer is about to be deleted.

**The observed behavior of the application**
Only the ID {{ID}} is presented for the user. 

**Information about your environment/platform**
Found in .Net v2.0.352.0
Not tested in .Net Core
Tested on:
- OSX
- Windows
- Ubuntu

**Comment by Gid733** [comment]
Fixed in #12 and #13 for .NET Core/.NET
